// Verifies with a real `astro build` that a `base` containing non-ASCII characters (a Japanese
// directory name, percent-encoded in URLs) builds and produces usable paths.
// Astro keeps `base` as it is written, while Vite percent-encodes it into the URLs of the assets
// it emits. Astro's local image services compare the two as plain strings, so such a base used
// to break the build (see src/imageService.ts).
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { before, describe, it } from 'node:test';
import { buildFixtureSiteOrThrow, listFiles } from './buildFixtureSite.ts';

const BASE = '/日本語ディレクトリ/';
/** How the base appears in URLs generated by Vite (image assets, CSS, scripts). */
const ENCODED_BASE = encodeURI(BASE);

let distDir: string;
let distFiles: string[];

before(async () => {
	const result = await buildFixtureSiteOrThrow({
		docsFixture: 'fixtures/docs',
		name: 'build-nonascii-base',
		base: BASE,
	});
	distDir = result.distDir;
	distFiles = await listFiles(distDir);
});

function html(relativePath: string): string {
	const file = path.join(distDir, relativePath);
	assert.ok(existsSync(file), `${relativePath} was not generated`);
	return readFileSync(file, 'utf-8');
}

describe('a base containing non-ASCII characters', () => {
	it('builds every page', () => {
		for (const page of ['index.html', 'en/index.html', 'alpha/index.html', 'gamma/guide/index.html']) {
			assert.ok(distFiles.includes(page), `${page} was not generated`);
		}
	});

	it('outputs the pages under dist itself, not under a directory named after the base', () => {
		const inBase = distFiles.filter((file) => file.startsWith(`${BASE.slice(1)}`));
		assert.deepEqual(inBase, [], `files were generated under the base directory: ${inBase.join(', ')}`);
	});

	it('images point at an existing file through the encoded base, added exactly once', () => {
		const images = [...html('alpha/index.html').matchAll(/<img[^>]*>/g)].map((match) => match[0]);
		assert.equal(images.length, 2, 'expected two images, one from Markdown syntax and one from raw HTML');
		for (const image of images) {
			const src = /src="([^"]+)"/.exec(image)?.[1];
			assert.ok(src, `no src: ${image}`);
			assert.ok(src.startsWith(`${ENCODED_BASE}_astro/`), `unexpected image URL: ${src}`);
			assert.ok(
				existsSync(path.join(distDir, decodeURI(src).slice(BASE.length))),
				`the referenced file is missing: ${src}`
			);
		}
	});

	it('links of the document list carry the base', () => {
		const list = /<ul>([\s\S]*?)<\/ul>/.exec(html('index.html'))?.[1];
		assert.ok(list, 'no <ul> for the document list');
		const hrefs = [...list.matchAll(/<a href="([^"]+)">/g)].map((match) => match[1] as string);
		assert.deepEqual(hrefs, [`${BASE}alpha/`, `${BASE}beta/`, `${BASE}gamma/guide/`]);
	});
});
