// Verifies with a real `astro build` that a `base` containing non-ASCII characters (a Japanese
// directory name, percent-encoded in URLs) builds and produces usable paths.
// Astro compares `base` as it is written against paths that are already percent-encoded, so such
// a base breaks everywhere it is compared: the build, the routing, the links Starlight generates.
// The site is therefore built under an ASCII placeholder base and the output is rewritten to the
// real one afterwards (see src/portableBase.ts); this is what checks that the rewrite covers
// every place a base ends up in.
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { before, describe, it } from 'node:test';
import { buildFixtureSiteOrThrow, listFiles } from './buildFixtureSite.ts';
import { BUILD_BASE } from '../../src/portableBase.ts';

const BASE = '/日本語ディレクトリ/';
/** How the base appears in URLs generated by Vite (image assets, CSS, scripts). */
const ENCODED_BASE = encodeURI(BASE);

let distDir: string;
let distFiles: string[];

before(async () => {
	const result = await buildFixtureSiteOrThrow({
		docsFixture: 'fixtures/docs',
		name: 'build-nonascii-base',
		base: BASE,
	});
	distDir = result.distDir;
	distFiles = await listFiles(distDir);
});

function html(relativePath: string): string {
	const file = path.join(distDir, relativePath);
	assert.ok(existsSync(file), `${relativePath} was not generated`);
	return readFileSync(file, 'utf-8');
}

describe('a base containing non-ASCII characters', () => {
	it('builds every page', () => {
		for (const page of ['ja/index.html', 'en/index.html', 'ja/alpha/index.html', 'ja/gamma/guide/index.html']) {
			assert.ok(distFiles.includes(page), `${page} was not generated`);
		}
	});

	it('outputs the pages under dist itself, not under a directory named after the base', () => {
		const inBase = distFiles.filter((file) => file.startsWith(`${BASE.slice(1)}`));
		assert.deepEqual(inBase, [], `files were generated under the base directory: ${inBase.join(', ')}`);
	});

	it('images point at an existing file through the encoded base, added exactly once', () => {
		const images = [...html('ja/alpha/index.html').matchAll(/<img[^>]*>/g)].map((match) => match[0]);
		assert.equal(images.length, 2, 'expected two images, one from Markdown syntax and one from raw HTML');
		for (const image of images) {
			const src = /src="([^"]+)"/.exec(image)?.[1];
			assert.ok(src, `no src: ${image}`);
			assert.ok(src.startsWith(`${ENCODED_BASE}_astro/`), `unexpected image URL: ${src}`);
			assert.ok(
				existsSync(path.join(distDir, decodeURI(src).slice(BASE.length))),
				`the referenced file is missing: ${src}`
			);
		}
	});

	it('the language switcher points at the same page under the other locale', () => {
		// Starlight compares `base` against the current path to swap the locale segment, which only
		// works because it does that against the ASCII base the site is built under: with the real
		// base it would put the locale in front of it ('/en/<base>/…') and 404 on switching.
		const options = (page: string): string[] =>
			[...page.matchAll(/<option value="([^"]*)"[^>]*>[^<]*<\/option>/g)]
				.map((match) => match[1] as string)
				// Both the desktop and the mobile header render the switcher.
				.filter((value, index, values) => values.indexOf(value) === index);

		assert.deepEqual(options(html('ja/alpha/index.html')), [
			`${ENCODED_BASE}ja/alpha/`,
			`${ENCODED_BASE}en/alpha/`,
		]);
		assert.deepEqual(options(html('en/alpha/index.html')), [
			`${ENCODED_BASE}ja/alpha/`,
			`${ENCODED_BASE}en/alpha/`,
		]);
	});

	it('recognises the locale of a page rendered by <StarlightPage>', () => {
		// The locale of the top pages comes from the path with the base stripped off as well.
		assert.match(html('ja/index.html'), /<html[^>]*lang="ja"/);
		assert.match(html('en/index.html'), /<html[^>]*lang="en"/);
	});

	it('the redirect at the site root points at the default locale through the encoded base', () => {
		// The target of the redirect goes into a Location header, which is no place for a raw
		// non-ASCII base (see the `redirects` entry in astro.config.mjs).
		const page = html('index.html');
		assert.match(page, new RegExp(`<meta http-equiv="refresh" content="0;url=${ENCODED_BASE}ja/">`));
	});

	it('links of the document list carry the encoded base', () => {
		// Built from import.meta.env.BASE_URL (src/components/DocumentIndex.astro), so these go
		// through the rewrite like every other URL.
		const list = /<ul>([\s\S]*?)<\/ul>/.exec(html('ja/index.html'))?.[1];
		assert.ok(list, 'no <ul> for the document list');
		const hrefs = [...list.matchAll(/<a href="([^"]+)">/g)].map((match) => match[1] as string);
		assert.deepEqual(hrefs, [
			`${ENCODED_BASE}ja/alpha/`,
			`${ENCODED_BASE}ja/beta/`,
			`${ENCODED_BASE}ja/gamma/guide/`,
		]);
	});

	it('leaves no file under the placeholder base the site is built with', () => {
		const left = distFiles.filter((file) =>
			readFileSync(path.join(distDir, file)).includes(BUILD_BASE)
		);
		assert.deepEqual(left, [], `files still carrying ${BUILD_BASE}: ${left.join(', ')}`);
	});
});
